### ISSUE TITLE
strategie - w jakim pliku?

### ISSUE THREAD

**Issue by sigrond** [sigrond/procesy_rozproszone#1]
## W którym pliku uważacie, że powinny się znaleźć klasy strategii dziedziczące po wirtualnej strategii?
- Osobny plik na wszystkie
- Osobny plik na każdą z osobna, jak przystało na klasę
- W Controller.cpp
- W Model.cpp
- Jeszcze inaczej?

**Proszę o konstruktywne odpowiedzi z uzasadnieniem**

**Comment by anrog** [comment]
Ja bym powiedział tak: osobne pliki dla klasy bazowej, klasy dziedziczące albo do jednego, osobnego pliku, albo do wielu, w zależności od ilości kodu na klasę. Nie ma sensu rozwalać 200 linii kodu na 20 plików. Myślę, że jak plik po prostu stanie się upierdliwy w przeglądaniu, należałoby go podzielić.

Możemy też się spytać jakiegoś wydziałowego guru o opinię.
